name: tfsec

on:
  push:
    branches: [ "prod", "dev", "staging" ]
  pull_request:
    branches: [ "prod", "dev", "staging" ]
  schedule:
    - cron: '29 1 * * 5'

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: |
          tfsec . --minimum-severity LOW
